version: '3.3'

services:
  web:
    build: .
    expose:
      - "5000"
    depends_on:
      - "db"
    network_mode: "host"
    
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    network_mode: "host"

      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

# Names our volume
volumes:
  my-db:


